# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"%\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03txt\x18\x02 \x01(\t\"\x1a\n\x08LogReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"!\n\rMessagesReply\x12\x10\n\x08messages\x18\x01 \x03(\t2\x81\x01\n\x0eLoggingService\x12\x36\n\nLogMessage\x12\x13.logging.LogRequest\x1a\x11.logging.LogReply\"\x00\x12\x37\n\x0bGetMessages\x12\x0e.logging.Empty\x1a\x16.logging.MessagesReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=63
  _globals['_LOGREPLY']._serialized_start=65
  _globals['_LOGREPLY']._serialized_end=91
  _globals['_EMPTY']._serialized_start=93
  _globals['_EMPTY']._serialized_end=100
  _globals['_MESSAGESREPLY']._serialized_start=102
  _globals['_MESSAGESREPLY']._serialized_end=135
  _globals['_LOGGINGSERVICE']._serialized_start=138
  _globals['_LOGGINGSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
